---
engines:
languages:
  css:
    enabled: false
exclude_paths:
  - "packages/example-nextjs14"
  - "packages/example-nextjs14/*"
  - "packages/example-nextjs14/**"
  - "packages/example-nextjs14/**/*"
  - "packages/example-nextjs15"
  - "packages/example-nextjs15/*"
  - "packages/example-nextjs15/**"
  - "packages/example-nextjs15/**/*"
  - "packages/example-react-router6"
  - "packages/example-react-router6/*"
  - "packages/example-react-router6/**"
  - "packages/example-react-router6/**/*"
  - "packages/example-react-router"
  - "packages/example-react-router/*"
  - "packages/example-react-router/**"
  - "packages/example-react-router/**/*"
  - "packages/example-react"
  - "packages/example-react/*"
  - "packages/example-react/**"
  - "packages/example-react/**/*"
  - "packages/example-remix2"
  - "packages/example-remix2/*"
  - "packages/example-remix2/**"
  - "packages/example-remix2/**/*"
  - "packages/urlstate/**/*.test.ts"
  - "packages/urlstate/**/*.md"
  - "dist"
  - "dist/*"
  - "dist/**"
  - "dist/**/*"
  - "tests"
  - "tests/*"
  - "tests/**"
  - "tests/**/*"
  - ".github"
  - ".github/*"
  - ".github/**"
  - ".github/**/*"
  - ".vscode"
  - ".vscode/*"
  - ".vscode/**"
  - ".vscode/**/*"
  - "dependabot.yml"
  - ".codacy.yml"
  - "package.json"
  - "package-lock.json"
  - ".eslintrc.json"
  - "tsconfig.json"
  - "tsconfig.*.json"
  - "**.test.ts"
  - "*.test.ts"
  - "**.test.tsx"
  - "*.test.tsx"
  - "**.spec.ts"
  - "*.spec.ts"
  - "**.spec.tsx"
  - "**.config.*"
  - "*.config.*"
  - "*.env.ts"
  - "testUtils.ts"
  - "**.md"
  - "*.md"
include_paths:
  - "packages/urlstate/"
  - "packages/urlstate/*"
  - "packages/urlstate/**"
  - "packages/urlstate/**/*"
