---
engines:
languages:
  css:
    enabled: false
exclude_paths:
  - "packages/example-nextjs"
  - "packages/example-nextjs/*"
  - "packages/example-nextjs/**"
  - "packages/example-nextjs/**/*"
  - "packages/example-react"
  - "packages/example-react/*"
  - "packages/example-react/**"
  - "packages/example-react/**/*"
  - "packages/urlstate/**/*.test.ts"
  - "packages/urlstate/**/*.md"
  - ".github"
  - ".github/*"
  - ".github/**"
  - ".github/**/*"
  - ".vscode"
  - ".vscode/*"
  - ".vscode/**"
  - ".vscode/**/*"
  - "dependabot.yml"
  - ".codacy.yml"
  - "package.json"
  - "package-lock.json"
  - ".eslintrc.json"
  - "tsconfig.json"
  - "tsconfig.*.json"
  - "**/tests/**"
  - "**.test.ts"
  - "*.test.ts"
  - "**.test.tsx"
  - "*.test.tsx"
  - "**.spec.ts"
  - "*.spec.ts"
  - "**.spec.tsx"
  - "**.config.*"
  - "*.config.*"
  - "*.env.ts"
  - "testUtils.ts"
  - "**.md"
  - "*.md"
include_paths:
  - "packages/urlstate/**"
