import { expect, test } from '@playwright/test';

/**
 * What the landing serves, and to whom.
 *
 * `src/proxy.ts` answers `/` with the llms.txt when the caller is an agent —
 * `Accept: text/markdown`, or a user-agent on the reader list — and with the
 * rendered page for everyone else. The file is generated by
 * `scripts/generate-middleware-content.cjs`, so a change made in `proxy.ts` by
 * hand is gone at the next build; the fix belongs in the generator.
 *
 * Everything here is asserted over HTTP through the `request` fixture, so no
 * browser is involved and one project is enough.
 */
test.describe('Landing content negotiation (landing only)', () => {
  test.skip(({ browserName }) => browserName !== 'chromium', 'Chromium only');

  const BROWSER = {
    'user-agent':
      'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36',
    accept:
      'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
  };

  test('the Markdown variant is never cacheable', async ({ request }) => {
    const response = await request.get('/', {
      headers: { ...BROWSER, accept: 'text/markdown' },
    });

    expect(response.status()).toBe(200);
    expect(response.headers()['content-type']).toContain('text/markdown');

    // The one rule that matters, and on Next it is the only lever there is.
    // Shared caches key on the URL, Vercel's ISR store ignores `Vary`, and Next
    // overwrites `Vary` on App Router responses before it ever reaches the edge
    // — the HTML at `/` comes back varying on `rsc, next-router-state-tree, …`
    // with no `Accept` in sight. Served cacheable, the first agent to ask for
    // Markdown after a deploy pins this blob into the entry for `/` and every
    // human visitor afterwards gets a wall of plain text, at 200, so nothing
    // alerts. It happened on a sibling site. Do not relax this.
    expect(response.headers()['cache-control']).toBe('no-store');
  });

  test('the Markdown variant carries the same terms as robots.txt', async ({
    request,
  }) => {
    // A crawler that never fetched robots.txt has no other way to learn them.
    const response = await request.get('/', {
      headers: { ...BROWSER, accept: 'text/markdown' },
    });

    const signal = response.headers()['content-signal'];
    expect(signal).toBeDefined();

    const robots = await (await request.get('/robots.txt')).text();
    expect(robots).toContain(`Content-Signal: ${signal}`);
  });

  test('a coding agent gets Markdown from its user-agent alone', async ({
    request,
  }) => {
    // Most agents never send `Accept: text/markdown`; they arrive as a plain
    // HTTP client and take what comes back — and mostly not under their own
    // name either: Cursor is `got`, Windsurf is `colly`, Claude Code is
    // `axios`. The library signature is the only thing on the request.
    for (const ua of [
      'curl/8.15.0',
      'Claude-User/1.0',
      'python-requests/2.32',
      'axios/1.8.4',
      'got (https://github.com/sindresorhus/got)',
      'colly - https://github.com/gocolly/colly',
      'DuckAssistBot/1.0',
      'MistralAI-User/1.0',
    ]) {
      const response = await request.get('/', {
        headers: { 'user-agent': ua, accept: '*/*' },
      });
      expect(
        response.headers()['content-type'],
        `${ua} should be served Markdown`,
      ).toContain('text/markdown');
    }
  });

  test('crawlers and headless browsers are always served HTML', async ({
    request,
  }) => {
    // A crawler and a reader must be served the same representation — that is
    // the line between a Markdown variant and cloaking. The Anthropic entries
    // are the interesting ones: every bulk crawler whose name contains a token
    // from the reader list has to be named in HTML_ONLY to be caught, and
    // Claude-Web and anthropic-ai once weren't.
    for (const ua of [
      'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
      'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/141.0.0.0 Safari/537.36',
      'Mozilla/5.0 (compatible; ClaudeBot/1.0; +claudebot@anthropic.com)',
      'Claude-Web/1.0',
      'anthropic-ai',
      'Mozilla/5.0 (compatible; GPTBot/1.2; +https://openai.com/gptbot)',
      'facebookexternalhit/1.1',
    ]) {
      const response = await request.get('/', {
        headers: { 'user-agent': ua, accept: '*/*' },
      });
      expect(
        response.headers()['content-type'],
        `${ua} should be served HTML`,
      ).toContain('text/html');
    }
  });

  test('`text/plain` counts only when it outranks `text/html`', async ({
    request,
  }) => {
    const preferred = await request.get('/', {
      headers: { ...BROWSER, accept: 'text/plain, text/html;q=0.9' },
    });
    expect(preferred.headers()['content-type']).toContain('text/plain');

    // A browser lists text/plain too, below text/html. That is not a request
    // for Markdown, and reading it as one would hand every Firefox user a wall
    // of text.
    const incidental = await request.get('/', {
      headers: {
        ...BROWSER,
        accept:
          'text/html,application/xhtml+xml,application/xml;q=0.9,text/plain;q=0.8,*/*;q=0.5',
      },
    });
    expect(incidental.headers()['content-type']).toContain('text/html');
  });

  test('a browser gets the rendered page', async ({ request }) => {
    const response = await request.get('/', { headers: BROWSER });

    expect(response.status()).toBe(200);
    expect(response.headers()['content-type']).toContain('text/html');
    expect(await response.text()).toContain('<!DOCTYPE html>');
  });

  test('the HTML is CDN-cacheable while the Markdown is not', async ({
    request,
  }) => {
    // The pairing is the point, so both halves are asserted together. `/` is
    // dynamic — it renders the demo from the query string — but Vercel's CDN
    // key is the full request URL, so each distinct state gets its own entry
    // and caching it cannot serve the wrong one. The Markdown variant is the
    // opposite case: same URL, second representation, negotiated partly on
    // user-agent, which no cache key contains. Hence `no-store` there and only
    // there. Loosening either half breaks the other's safety.
    for (const path of ['/', '/?name=cached']) {
      const html = await request.get(path, { headers: BROWSER });
      const cacheControl = html.headers()['cache-control'] ?? '';

      expect(cacheControl, `${path} should be CDN-cacheable`).toContain(
        's-maxage',
      );
      expect(cacheControl).not.toContain('no-store');
    }

    const markdown = await request.get('/', {
      headers: { ...BROWSER, accept: 'text/markdown' },
    });
    expect(markdown.headers()['cache-control']).toBe('no-store');
  });

  test('the .md mirrors are single-representation, and so do cache', async ({
    request,
  }) => {
    // Unlike `/`, these URLs have one representation each: nothing behind them
    // can be handed to the wrong caller, so they are ordinary static assets.
    for (const path of ['/index.md', '/react-router.md', '/remix.md']) {
      const response = await request.get(path, { headers: BROWSER });

      expect(response.status(), `${path} should exist`).toBe(200);
      expect(response.headers()['content-type']).toContain('text/markdown');
      expect(response.headers()['cache-control']).not.toContain('no-store');
    }
  });
});
